### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by Haxrox** [Haxrox/Haxdroid#1]
Upgrade all packages to latest versions (especially Discord.js)

- [x] Discord.js
- [x] Axios 
- [x] ytdl

**Comment by WorldofKerry** [comment]
I highly recommend delendabot
https://github.com/dependabot
It autoupdates packages without breaking changes.

**Comment by Haxrox** [comment]
Currently, many packages are outdated and have been re-architectured.

The scope of this issue is to fix logic that is caused by upgrading packages.

I will look into adding dependabot to autoupdate packages though
